### ISSUE TITLE
Remove "Powered by Freshchat"

### ISSUE THREAD

**Issue by danilobuerger** [freshdesk/freshchat-ios#10]
Is it possible to remove the "Powered by Freshchat" text beneath the input?

**Comment by harish-kumarc** [comment]
@danilobuerger We can help you with technical queries only here. Our support team or your account manager would be able to assist you regarding this, please email us at support@freshchat.com

**Comment by danilobuerger** [comment]
@harish-kumarc but that's what I am asking: Is it **technically** possible, for example through a config flag, to remove the "Powered by Freshchat" text?

**Comment by harish-kumarc** [comment]
Its technically possible. Please reach out to our team at support@freshchat.com for further assistance.

**Comment by gkye** [comment]
Any update on this?

**Comment by danilobuerger** [comment]
@gkye I stopped looking into freshchat after this as I found this to be somewhat intransparent.

**Comment by tryprasannan** [comment]
@gkye @danilobuerger We've shared its technically possible. Your account manager is the best person to help you with this. Otherwise you can  always email our team at  support@freshchat.com for further assistance regarding this

**Comment by bartread** [comment]
@tryprasannan We have the same issue: @harish-kumarc could have posted a link to the relevant online documentation in response to @danilobuerger instead of simply being unhelpful/facetious.

If you don't have any online documentation he could have explained that, which would also explain the need to contact support. In general most people don't appreciate having to contact an account manager (or, for that matter, support) to resolve a simple technical query. One reason for this is that it turns what should be a quick and simple question and answer into an ongoing dialogue that takes too long too resolve.

You should also know that this page is the top result on Google when searching for information about how to hide the "By freshchat" text in chat windows so, again, it would seem sensible (and good customer service) for you to post a link to the relevant information here.

**Comment by bartread** [comment]
3rd result on Google: https://support.freshchat.com/support/solutions/articles/238304-can-i-remove-the-powered-by-freshchat-from-the-chat-widget-

_We’re a relatively young and growing business and would love to have your brand’s support in spreading our philosophy.

That being said, we would like to understand how important it is for your website and its template to not have the Freshchat branding on the widget. Please do write to support@freshchat.com regarding the same._

This is nearly as unhelpful as the responses above. Can you please implement a simple way of doing this in your settings UI? I don't want an advert for Freshchat in the middle of our flagship product. **That's** how important it is to me.

**Comment by dippa87** [comment]
Did anyone ever find a solution to this ? 

For a premium product, this should already be a feature! I can understand the need to have advertisement if the person hasn't purchased it, but for the ones who have paid... this should be an option for us to have this removed!

If this isn't resolved in the near future, then I will not be using this product for much longer

**Comment by jkestner** [comment]
I was able to remove this by method swizzling viewWillAppear in FCContainerView, and hiding FCFooterView there. But that since broke, and I haven't had time to pick it back up.
