### ISSUE TITLE
Crash with CoreData

### ISSUE THREAD

**Issue by eshwartm** [freshdesk/freshchat-ios#2]
There is a crash with this message. `CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter`

`let freshChatConfig: FreshchatConfig = FreshchatConfig(appID: FRESHCHAT_APP_ID, andAppKey: FRESHCHAT_APP_KEY)`
 `Freshchat.sharedInstance().initWith(freshChatConfig)` <- It happened on this line.

**Comment by SanjithKanagavel** [comment]
Hey Eshwar, 

Thanks for reaching us. This error has potentially caused because of Freshchat core-data model not loaded properly to the project.  Would recommend the following methods to debug this out. 

- Please confirm FreshchatModels.bundle in FreshchatSDK pod has included the current project in Target Membership.
- Try clearing xcode derived data, clean & rebuild the project again. 
- Try re-installing FreshchatSDK pod again. 
- Please make sure mac has enough storage space to run the project.

Please try them and let us know.

**Comment by harish-kumarc** [comment]
@eshwartm This will happen only if the core data models did not load correctly. Closing this as we haven't heard from you. Please reply here to reopen or contact to support@freshchat.com

**Comment by kalidosstesark** [comment]
am also facing same issues 

#  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

2018-04-13 13:24:01.636225+0530 MyApp[18630:161588] [error] error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter

**Comment by harish-kumarc** [comment]
Hi @kalidosstesark , Can you please try the steps mentioned by @SanjithKanagavel above. Let us know if the issue still persists after that. 

Thanks

**Comment by iranjith4** [comment]
The same crash happened to me.

```2018-05-25 11:13:52.846026+0530 APPNAME[398:30142] [error] error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter
CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter
2018-05-25 11:13:53.277933+0530 APPNAME[398:30142] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x18169ed8c ........0x180ff5fc0)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Just cleaned the project and ran it. Works fine. Thanks @SanjithKanagavel
