### ISSUE TITLE
push notification(APN) 

### ISSUE THREAD

**Issue by narendraksp** [freshdesk/freshchat-ios#72]
i am not receiving push notification(APN) in ios13  iPhones but   I am getting notification in  lower version( ios 12.x and below)

**Comment by harish-kumarc** [comment]
Hi @narendraksp , There was an issue where if you are using SDK version less than v2.8.0 with Xcode 11 then push notification are failing with iOS 13+ devices. This is fixed with release [v2.8.0](https://github.com/freshdesk/freshchat-ios/releases/tag/v2.8.0). Can you please update to latest SDK version and let us know if this fixes the issue.

**Comment by narendraksp** [comment]
@harish-kumarc Now its working fine, thanks for the solution
